name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Introduction
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: introduction.svg
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_lines: yes
          plugin_traffic: yes
    
      - name: Languages
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_details: lines, percentage
          commits_authoring: thimo@th7mo.nl, thimoquinten@gmail.com
          plugin_languages_ignored: Dart, html, css, sass, scss, dockerfile, makefile, shell, cmake
          plugin_languages_skipped: Th7mo/F12_Mobile
          plugin_languages_aliases: RenderScript:Rust
