name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          config_timezone: Europe/Amsterdam        
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_details: lines
          commits_authoring: thimo@th7mo.nl, thimoquinten@gmail.com
          plugin_languages_ignored: Dart, html, css, sass, scss, dockerfile, makefile, shell, cmake
          plugin_languages_skipped: Th7mo/F12_Mobile
          plugin_languages_aliases: RenderScript:Rust
          
          plugin_habits: yes
          plugin_habits_days: 30
          plugin_habits_charts_type: chartist
          plugin_habits_facts: no
          
          plugin_lines: yes
